[package]
name = "i2c"
version = "0.1.0"
authors = ["starfish-bee <77985573+starfish-bee@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.92"
